openapi: 3.0.3
info:
  title: Family Car Tracker - OpenAPI 3.0
  description: |-
    This is a sample family car tracking application allowing us to book car usage times.
    
    Since I'm are using cookie auth on this Family Car project, the Try It Out feature won't work in browsers due to security limitations. Please use Postman to try these requests
  contact:
    email: kushliansky@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://18qv4o7xm9.execute-api.eu-west-1.amazonaws.com
paths:
  /login:
    post:
      summary: Login with your credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: masha
                  password:
                    type: string
                    example: myPassW0rd
        '401':
          description: Unauthorized. Invalid credentials presented
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'Invalid username or password provided'

components:
  schemas:
    Login:
      type: object
      properties:
        username:
          type: string
          example: masha
        password:
          type: string
          example: myPassW0rd
  # 1) Define the cookie name
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: sessionId  # cookie name
# 2) Apply cookie auth globally to all operations
security:
  - cookieAuth: []

